export const DEFAULT_SEND_AND_WAIT_TIMEOUT_SECONDS = 10 * 60;
export const DEFAULT_SEND_AND_WAIT_TIMEOUT_MS =
  DEFAULT_SEND_AND_WAIT_TIMEOUT_SECONDS * 1_000;
export const DEFAULT_SESSION_HELPER_COUNTDOWN_MS =
  DEFAULT_SEND_AND_WAIT_TIMEOUT_MS;
